AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Coinbase Price Tracker API - Spring Boot Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage

  TwitterBearerToken:
    Type: String
    Default: ""
    NoEcho: true
    Description: Twitter/X API Bearer Token for sentiment analysis

  VonageApiKey:
    Type: String
    Default: ""
    NoEcho: true
    Description: Vonage API Key for SMS notifications

  VonageApiSecret:
    Type: String
    Default: ""
    NoEcho: true
    Description: Vonage API Secret for SMS notifications

  VonageFromNumber:
    Type: String
    Default: "14157386102"
    Description: Vonage WhatsApp sandbox number

  AnalysisLambdaFunctionName:
    Type: String
    Default: "crypto-analysis-dev"
    Description: Name of the crypto analysis Lambda function

Resources:
  # S3 Bucket for Subscribers
  SubscribersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "crypto-subscribers-${Stage}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: coinbase-price-tracker
        - Key: Stage
          Value: !Ref Stage

  # Cognito User Pool for authentication
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      UsernameAttributes:
        - phone_number
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: phone_number
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      UserPoolTags:
        Application: coinbase-price-tracker
        Stage: !Ref Stage

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-client
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
  # DynamoDB Tables
  EnrollmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub symbol-enrollments-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: symbol
          AttributeType: S
      KeySchema:
        - AttributeName: symbol
          KeyType: HASH
      Tags:
        - Key: Application
          Value: coinbase-price-tracker
        - Key: Stage
          Value: !Ref Stage

  PriceHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub price-history-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: symbol
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: symbol
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: coinbase-price-tracker
        - Key: Stage
          Value: !Ref Stage

  CoinbasePriceTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub coinbase-price-tracker-${Stage}
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      CodeUri: .
      Description: Coinbase Price Tracker API
      MemorySize: 1024
      Timeout: 60
      Environment:
        Variables:
          MAIN_CLASS: com.tracker.Application
          SPRING_CLOUD_FUNCTION_DEFINITION: apiHandler
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          AWS_DYNAMODB_TABLES_ENROLLMENT: !Ref EnrollmentTable
          AWS_DYNAMODB_TABLES_PRICE_HISTORY: !Ref PriceHistoryTable
          TWITTER_BEARER_TOKEN: !Ref TwitterBearerToken
          AWS_S3_SUBSCRIBERS_BUCKET: !Ref SubscribersBucket
          VONAGE_API_KEY: !Ref VonageApiKey
          VONAGE_API_SECRET: !Ref VonageApiSecret
          VONAGE_FROM_NUMBER: !Ref VonageFromNumber
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref CoinbaseApi
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref CoinbaseApi
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt EnrollmentTable.Arn
                - !GetAtt PriceHistoryTable.Arn
            - Effect: Allow
              Action:
                - comprehend:DetectSentiment
                - comprehend:BatchDetectSentiment
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !GetAtt SubscribersBucket.Arn
                - !Sub "${SubscribersBucket.Arn}/*"
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:AdminRespondToAuthChallenge
                - cognito-idp:AdminSetUserPassword
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminConfirmSignUp
                - cognito-idp:SignUp
                - cognito-idp:ConfirmSignUp
                - cognito-idp:InitiateAuth
                - cognito-idp:RespondToAuthChallenge
              Resource:
                - !GetAtt CognitoUserPool.Arn

  CoinbaseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"

  # Notification Lambda - Scheduled daily to send price SMS
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub crypto-notification-${Stage}
      Handler: com.tracker.NotificationHandler::handleRequest
      CodeUri: .
      Description: Sends daily crypto price SMS notifications
      MemorySize: 1024
      Timeout: 120
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: lambda
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          AWS_S3_SUBSCRIBERS_BUCKET: !Ref SubscribersBucket
          AWS_DYNAMODB_TABLES_PRICE_HISTORY: !Ref PriceHistoryTable
          VONAGE_API_KEY: !Ref VonageApiKey
          VONAGE_API_SECRET: !Ref VonageApiSecret
          VONAGE_FROM_NUMBER: !Ref VonageFromNumber
          ANALYSIS_LAMBDA_FUNCTION_NAME: !Ref AnalysisLambdaFunctionName
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 * * ? *)
            Description: Trigger daily price notifications at 6 AM EST
            Enabled: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !GetAtt SubscribersBucket.Arn
                - !Sub "${SubscribersBucket.Arn}/*"
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AnalysisLambdaFunctionName}"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt PriceHistoryTable.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${CoinbaseApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt CoinbasePriceTrackerFunction.Arn

  FunctionName:
    Description: Lambda Function Name
    Value: !Ref CoinbasePriceTrackerFunction

  EnrollmentTableName:
    Description: DynamoDB table for symbol enrollments
    Value: !Ref EnrollmentTable

  EnrollmentTableArn:
    Description: DynamoDB enrollment table ARN
    Value: !GetAtt EnrollmentTable.Arn

  PriceHistoryTableName:
    Description: DynamoDB table for price history
    Value: !Ref PriceHistoryTable

  PriceHistoryTableArn:
    Description: DynamoDB price history table ARN
    Value: !GetAtt PriceHistoryTable.Arn

  SubscribersBucketName:
    Description: S3 bucket for phone number subscribers
    Value: !Ref SubscribersBucket

  SubscribersBucketArn:
    Description: S3 subscribers bucket ARN
    Value: !GetAtt SubscribersBucket.Arn

  NotificationFunctionArn:
    Description: Notification Lambda Function ARN
    Value: !GetAtt NotificationFunction.Arn

  NotificationFunctionName:
    Description: Notification Lambda Function Name
    Value: !Ref NotificationFunction

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
